<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="PO CAN Travel — pesan tiket bus dengan jadwal dan kursi pilihan Anda.">
    <title>PO CAN Travel — Pemesanan Tiket Bus</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-white text-slate-800 antialiased">
<header class="border-b border-slate-200 bg-white"><nav class="site-shell flex h-16 items-center justify-between"><a href="{{ route('home') }}" class="flex items-center gap-2.5 font-bold tracking-tight text-brand-950"><span class="flex h-8 w-8 items-center justify-center rounded-md bg-brand-950 text-sm font-black text-amber-300">C</span>{{ $settings['app_name'] ?? 'PO CAN Travel' }}</a><div class="flex items-center gap-2 text-sm font-semibold"><a href="{{ route('customer.trips.index') }}" class="hidden rounded-md px-3 py-2 text-slate-600 hover:bg-slate-50 sm:block">Jadwal</a>@auth<a href="{{ auth()->user()->role === 'admin' ? route('admin.dashboard') : route('customer.dashboard') }}" class="btn-primary min-h-9 px-3 py-1.5">Dashboard</a>@else<a href="{{ route('login') }}" class="rounded-md px-3 py-2 text-slate-600 hover:bg-slate-50">Masuk</a><a href="{{ route('register') }}" class="btn-primary min-h-9 px-3 py-1.5">Daftar</a>@endauth</div></nav></header>
<main>
<section class="border-b border-slate-200 bg-slate-50"><div class="site-shell grid gap-10 py-12 sm:py-16 lg:grid-cols-[1.05fr_.95fr] lg:items-end lg:py-20"><div class="max-w-2xl"><p class="eyebrow">Tiket bus, tanpa antre</p><h1 class="mt-4 text-4xl font-bold tracking-tight text-brand-950 sm:text-5xl sm:leading-[1.08]">Jadwal yang jelas. Perjalanan yang lebih tenang.</h1><p class="mt-5 max-w-xl text-base leading-7 text-slate-600">Cari rute, pilih kursi, dan simpan tiket perjalanan Anda dalam satu tempat. PO CAN Travel memudahkan perjalanan antarkota.</p></div><form method="GET" action="{{ route('customer.trips.index') }}" class="surface p-5 sm:p-6"><div class="mb-5"><h2 class="section-title">Cari perjalanan</h2><p class="mt-1 text-sm text-slate-500">Lengkapi detail keberangkatan Anda.</p></div><div class="grid gap-4 sm:grid-cols-2"><div><label for="origin_city" class="field-label">Kota asal</label><input id="origin_city" name="origin_city" required placeholder="Contoh: Jepara" class="w-full rounded-md border-slate-300 text-sm focus:border-brand-600 focus:ring-brand-600"></div><div><label for="destination_city" class="field-label">Kota tujuan</label><input id="destination_city" name="destination_city" required placeholder="Contoh: Jakarta" class="w-full rounded-md border-slate-300 text-sm focus:border-brand-600 focus:ring-brand-600"></div><div><label for="departure_date" class="field-label">Tanggal berangkat</label><input id="departure_date" name="departure_date" type="date" min="{{ now()->toDateString() }}" required class="w-full rounded-md border-slate-300 text-sm focus:border-brand-600 focus:ring-brand-600"></div><div><label for="passengers" class="field-label">Penumpang</label><select id="passengers" name="passengers" class="w-full rounded-md border-slate-300 text-sm focus:border-brand-600 focus:ring-brand-600"><option value="1">1 penumpang</option><option value="2">2 penumpang</option><option value="3">3 penumpang</option><option value="4">4 penumpang</option></select></div></div><button class="btn-primary mt-5 w-full">Cari jadwal perjalanan</button></form></div></section>
<section class="site-shell grid border-b border-slate-200 sm:grid-cols-3">@foreach([['01', 'Pilih jadwal', 'Temukan rute dan waktu yang sesuai.'], ['02', 'Pilih kursi', 'Lihat kursi tersedia sebelum memesan.'], ['03', 'Selesaikan pembayaran', 'Tiket tersedia setelah pembayaran berhasil.']] as [$number, $title, $copy])<div class="border-slate-200 py-6 sm:px-6 sm:first:pl-0 sm:not(:last-child):border-r"><p class="text-sm font-bold text-brand-700">{{ $number }}</p><h2 class="mt-2 font-semibold text-brand-950">{{ $title }}</h2><p class="mt-1 text-sm leading-6 text-slate-600">{{ $copy }}</p></div>@endforeach</section>
<section class="site-shell py-14 sm:py-20"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">Jadwal terdekat</p><h2 class="mt-2 text-3xl font-bold tracking-tight text-brand-950">Perjalanan yang dapat dipesan</h2></div><a href="{{ route('customer.trips.index') }}" class="text-sm font-semibold text-brand-700 hover:text-brand-950">Lihat semua jadwal →</a></div><div class="mt-8 divide-y divide-slate-200 border-y border-slate-200">@forelse($featuredRoutes as $route)<div class="grid gap-4 py-5 sm:grid-cols-[100px_minmax(0,1fr)_auto] sm:items-center"><div><p class="text-2xl font-bold tracking-tight text-brand-950">{{ \Carbon\Carbon::parse($route->departure_time)->format('H:i') }}</p><p class="mt-1 text-xs text-slate-500">{{ $route->departure_date->translatedFormat('d M Y') }}</p></div><div><p class="font-semibold text-brand-950">{{ $route->origin_city }} <span class="mx-2 text-slate-400">→</span> {{ $route->destination_city }}</p><p class="mt-1 text-sm text-slate-500">{{ $route->bus->bus_name }} · {{ ucfirst(str_replace('_', ' ', $route->bus->bus_type)) }} · {{ $route->available_seats }} kursi tersedia</p></div><div class="flex items-center justify-between gap-5 sm:block sm:text-right"><p class="font-bold text-brand-950">Rp {{ number_format($route->price, 0, ',', '.') }}</p><a href="{{ route('customer.trips.show', $route) }}" class="mt-1 inline-block text-sm font-semibold text-brand-700 hover:text-brand-950">Lihat detail</a></div></div>@empty<div class="py-10 text-sm text-slate-500">Belum ada jadwal yang tersedia saat ini.</div>@endforelse</div></section>
<section id="cara-memesan" class="bg-slate-50 py-14 sm:py-20"><div class="site-shell"><p class="eyebrow">Cara booking</p><div class="mt-2 grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><h2 class="text-3xl font-bold tracking-tight text-brand-950">Empat langkah menuju perjalanan Anda.</h2><ol class="grid gap-5 sm:grid-cols-2">@foreach(['Cari rute berdasarkan kota dan tanggal.', 'Pilih jadwal serta kursi yang tersedia.', 'Isi data penumpang dan periksa pesanan.', 'Bayar, lalu akses e-ticket Anda.'] as $step => $copy)<li class="border-t border-slate-300 pt-3"><span class="text-sm font-bold text-brand-700">0{{ $step + 1 }}</span><p class="mt-2 font-medium leading-6 text-brand-950">{{ $copy }}</p></li>@endforeach</ol></div></div></section>
<section id="kebijakan-pembatalan" class="site-shell grid gap-8 py-14 sm:py-20 lg:grid-cols-2"><div><p class="eyebrow">Informasi layanan</p><h2 class="mt-2 text-3xl font-bold tracking-tight text-brand-950">Rencanakan perjalanan dengan informasi yang mudah diakses.</h2></div><div class="space-y-5 text-sm leading-6 text-slate-600"><p>Setelah pembayaran berhasil, e-ticket dapat ditunjukkan saat check-in. Mohon datang setidaknya 30 menit sebelum keberangkatan.</p><p>{{ $settings['cancellation_policy'] ?? 'Untuk pembatalan atau pertanyaan seputar pesanan, hubungi tim PO CAN Travel.' }}</p></div></section>
<section class="bg-brand-950 py-12 text-white"><div class="site-shell flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-semibold text-amber-300">SIAP BERANGKAT?</p><h2 class="mt-1 text-2xl font-bold tracking-tight">Cari perjalanan Anda sekarang.</h2></div><a href="{{ route('customer.trips.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-md bg-amber-400 px-4 py-2.5 text-sm font-semibold text-brand-950 hover:bg-amber-300">Cari perjalanan</a></div></section>
</main>
<footer id="kontak" class="bg-white"><div class="site-shell grid gap-7 py-10 text-sm sm:grid-cols-3"><div><p class="font-bold text-brand-950">{{ $settings['app_name'] ?? 'PO CAN Travel' }}</p><p class="mt-2 leading-6 text-slate-500">{{ $settings['footer_address'] ?? 'Perjalanan antarkota yang lebih terencana.' }}</p></div><div><p class="font-semibold text-brand-950">Layanan</p><a href="{{ route('customer.trips.index') }}" class="mt-2 block text-slate-600 hover:text-brand-950">Jadwal perjalanan</a><a href="#cara-memesan" class="mt-1 block text-slate-600 hover:text-brand-950">Cara booking</a></div><div><p class="font-semibold text-brand-950">Hubungi kami</p><a href="mailto:{{ $settings['contact_email'] ?? 'support@pocantravel.com' }}" class="mt-2 block text-slate-600 hover:text-brand-950">{{ $settings['contact_email'] ?? 'support@pocantravel.com' }}</a><a href="tel:{{ $settings['contact_phone'] ?? '081234567890' }}" class="mt-1 block text-slate-600 hover:text-brand-950">{{ $settings['contact_phone'] ?? '081234567890' }}</a></div></div></footer>
</body></html>
