@extends('customer.layouts.index')

@section('title', 'Beranda — PO CAN Travel')

@section('content')
@php($nextOrder = $latestOrders->first(fn ($order) => in_array($order->order_status, ['pending', 'paid'], true)))
<div class="flex flex-col gap-5 border-b border-slate-200 pb-7 sm:flex-row sm:items-end sm:justify-between">
    <div><p class="eyebrow">Beranda</p><h1 class="page-heading mt-2">Halo, {{ auth()->user()->name }}</h1><p class="mt-2 text-sm text-slate-600">Semua kebutuhan perjalanan Anda, dalam satu tempat.</p></div>
    <a href="{{ route('customer.trips.index') }}" class="btn-primary w-full sm:w-auto">Cari perjalanan</a>
</div>

<section class="mt-8 surface p-5 sm:p-6"><div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="eyebrow">Booking cepat</p><h2 class="section-title mt-2">Ke mana Anda ingin pergi?</h2></div><form method="GET" action="{{ route('customer.trips.index') }}" class="grid w-full gap-3 sm:grid-cols-3 lg:max-w-3xl"><input name="origin_city" required placeholder="Kota asal" class="rounded-md border-slate-300 text-sm focus:border-brand-600 focus:ring-brand-600"><input name="destination_city" required placeholder="Kota tujuan" class="rounded-md border-slate-300 text-sm focus:border-brand-600 focus:ring-brand-600"><button class="btn-primary">Cari jadwal</button></form></div></section>

<div class="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]">
    <div class="space-y-8">
        <section><div class="flex items-center justify-between"><div><p class="eyebrow">Perjalanan berikutnya</p><h2 class="section-title mt-2">Rencana terdekat Anda</h2></div>@if($nextOrder)<a href="{{ route('customer.orders.show', $nextOrder) }}" class="text-sm font-semibold text-brand-700 hover:text-brand-950">Lihat pesanan →</a>@endif</div>
            @if($nextOrder)<article class="surface mt-4 grid gap-5 p-5 sm:grid-cols-[110px_minmax(0,1fr)_auto] sm:items-center sm:p-6"><div><p class="text-2xl font-bold text-brand-950">{{ \Carbon\Carbon::parse($nextOrder->route->departure_time)->format('H:i') }}</p><p class="mt-1 text-xs text-slate-500">{{ $nextOrder->route->departure_date->translatedFormat('d M Y') }}</p></div><div><p class="font-semibold text-brand-950">{{ $nextOrder->route->origin_city }} <span class="mx-2 text-slate-400">→</span> {{ $nextOrder->route->destination_city }}</p><p class="mt-1 text-sm text-slate-500">{{ $nextOrder->route->bus->bus_name }} · {{ $nextOrder->total_passengers }} penumpang</p></div><x-status-badge :status="$nextOrder->order_status" /></article>@else<div class="surface-muted mt-4 p-5"><p class="font-semibold text-brand-950">Belum ada perjalanan aktif</p><p class="mt-1 text-sm text-slate-600">Mulai dengan mencari jadwal yang sesuai untuk Anda.</p></div>@endif
        </section>
        <section><div class="flex items-end justify-between"><div><p class="eyebrow">Pesanan terbaru</p><h2 class="section-title mt-2">Riwayat booking</h2></div><a href="{{ route('customer.orders.index') }}" class="text-sm font-semibold text-brand-700 hover:text-brand-950">Lihat semua →</a></div><div class="mt-4 divide-y divide-slate-200 border-y border-slate-200">@forelse($latestOrders as $order)<a href="{{ route('customer.orders.show', $order) }}" class="grid gap-3 py-4 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center hover:bg-slate-50"><div><p class="font-semibold text-brand-950">{{ $order->route->origin_city }} → {{ $order->route->destination_city }}</p><p class="mt-1 text-sm text-slate-500">{{ $order->order_code }} · {{ $order->route->departure_date->translatedFormat('d M Y') }}</p></div><x-status-badge :status="$order->payment?->status" type="payment" /><p class="font-semibold text-brand-950">Rp {{ number_format($order->total_price, 0, ',', '.') }}</p></a>@empty<p class="py-8 text-sm text-slate-500">Belum ada riwayat pesanan.</p>@endforelse</div></section>
    </div>
    <aside class="surface h-fit p-5 sm:p-6"><p class="eyebrow">Ringkasan akun</p><dl class="mt-5 divide-y divide-slate-200"><div class="flex items-center justify-between py-3"><dt class="text-sm text-slate-600">Total pesanan</dt><dd class="font-bold text-brand-950">{{ $stats['total_orders'] }}</dd></div><div class="flex items-center justify-between py-3"><dt class="text-sm text-slate-600">Menunggu pembayaran</dt><dd class="font-bold text-amber-700">{{ $stats['pending_orders'] }}</dd></div><div class="flex items-center justify-between py-3"><dt class="text-sm text-slate-600">Perjalanan selesai</dt><dd class="font-bold text-brand-950">{{ $stats['completed_orders'] }}</dd></div></dl><a href="{{ route('profile.edit') }}" class="btn-secondary mt-5 w-full">Kelola profil</a></aside>
</div>
@endsection
